### ISSUE TITLE
Deliverables for v1.1

### ISSUE THREAD

**Issue by kangmingtay** [CS2113-AY1819S1-F09-2/main#13]
Kang Ming: Implement a view members feature which displays the data from the members.txt file

**Comment by kianhong95** [comment]
Kian Hong: Implement a view employees feature which displays data from the employees.txt file

**Comment by AngWM** [comment]
Wei Ming: Integrate all the various features together

**Comment by px1099** [comment]
Pham Minh: 
- Implement classes for Ordering feature and store it in orderlist.txt
- Implement `listorder` command to view all orders in the order list
