### ISSUE TITLE
Name of .jar file inaccurate

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-F09-2/main#145]
**Describe the bug**
Despite the name of the app being "Restaurant Management System", the .jar file has a name `addressbook,jar`.

**To Reproduce**
1. Download the .jar file

**Expected behavior**
The .jar file should have a name `Restaurant Management System.jar` or similar.

<hr>

**Reported by:** @nianfei97
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#3]</sub>

**Comment by px1099** [comment]
All released jar files now have been renamed to: `RestaurantManagementSystem-v1.x.jar`
