### ISSUE TITLE
Incorrect error message when using add command

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-F09-2/main#148]
**Describe the bug**
The error message shown when an invalid `add` command is executed still refers to an Address Book.

**To Reproduce**
1.  Type `add` in the command box.
2. Press `Enter`. 

**Expected behavior**
An error message specific to the RMS is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/35740636/47905567-64be1280-dec2-11e8-9ead-1e5a911e0515.png)

<hr>

**Reported by:** @nianfei97
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#78]</sub>

**Comment by px1099** [comment]
Closed.
Reason: being the subproblem of #160
