### ISSUE TITLE
Command listed in user guide does not work

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-F09-2/main#149]
**Describe the bug**
listmenubytype does not work

**To Reproduce**
1. Start the programme
2. Enter: 'addmenu Ice Cream p/$15.00 type/Dessert
3. Enter: 'listmenubytype dessert'

**Expected behavior**
I expect to see a list of all desserts previously entered. In this case, the Ice Cream. Instead, I see an entire list of commands supposedly possible. 

**Screenshots**

**Additional context**

<hr>

**Reported by:** @dyeosy98
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#91]</sub>

**Comment by px1099** [comment]
Closed.
Reason: being the same problem as #168
