### ISSUE TITLE
Example command given in UG cannot be executed

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-F09-2/main#150]
**Describe the bug**
The example command, which has a wrong command word, does not work.

`addmenu Cheese Fries p/$3.50 type/sides t/New item`

**To Reproduce**
1. Type `addmenu Cheese Fries p/$3.50 type/sides t/New item` in the command box.
2. Press `Enter`.

**Expected behavior**
A new item gets added to the menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/35740636/47905825-fc236580-dec2-11e8-91c5-69f9324db3cf.png)

**Additional context**
This is probably due to the space bar in the tag `New item`.

<hr>

**Reported by:** @nianfei97
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#122]</sub>

**Comment by px1099** [comment]
Closed.
Reason: being the same problem as #151
