### ISSUE TITLE
The command viewallmenu does not work.

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-F09-2/main#153]
**Describe the bug**
In section 3.1.6 of the UG, the command `viewallmenu` is described without any arguments. However, this command does not work.

**To Reproduce**
1. Type `viewallmenu` in the command box.
2. Press `Enter`.

**Expected behavior**
The menu is shown.

**Screenshots**
Relevant section of UG:
![image](https://user-images.githubusercontent.com/35740636/47906043-60462980-dec3-11e8-86c5-8c73db9ca94b.png)

Actual behaviour:
![image](https://user-images.githubusercontent.com/35740636/47906075-705e0900-dec3-11e8-99ec-22209c074065.png)

<hr>

**Reported by:** @nianfei97
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#156]</sub>

**Comment by px1099** [comment]
Need a fix to user guide

**Comment by px1099** [comment]
Closed.
Reason: being the same problem as #158
