### ISSUE TITLE
addmenu command does not accept more than two decimal places for cents in the price

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-F09-2/main#154]
**Describe the bug**
addmenu command does not accept more than two decimal places for cents in the price.

**To Reproduce**
1. Enter "addmenu Spam Fries p/$3.000 type/sides t/New"
2. Press ENTER key
4. See error message: "Price should be in SGD and in dollars and cents."

**Expected behavior**
The item "Spam Fries" should have been added to the "sides" menu as it had a valid price of $3.000 

**Screenshots**
Input entered:
![image](https://user-images.githubusercontent.com/35756915/47906188-abf8d300-dec3-11e8-9c16-e373a235c627.png)

Error encountered:
![image](https://user-images.githubusercontent.com/35756915/47906253-cf238280-dec3-11e8-8982-e0882d3d44bb.png)

<hr>

**Reported by:** @jeremyinelysium
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#217]</sub>

**Comment by px1099** [comment]
Need better error message
