### ISSUE TITLE
Unable to view item even after adding item to menu

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-F09-2/main#156]
**Describe the bug**
After adding an item to the menu, the item cannot be seen when using `viewallmenu`.

**To Reproduce**
1. Run `listmenu`.
2. Add an item to the menu using `addmenu`, for example, `addmenu Cheese Fries p/$3.50 type/sides t/Newitem`
3. Run `viewallmenu 1`.

**Expected behavior**
A menu with the added item appears.

**Screenshots**
Error message:
![image](https://user-images.githubusercontent.com/35740636/47906388-1a3d9580-dec4-11e8-8328-ff3e44ff3255.png)

**Additional context**
I am unsure as to what the command `viewallmenu` is supposed to do. From the name of the command, it appears to be a command that allows one to either:
1) view all items on the menu, or
2) view all the menus in the app

Point 1 appears to be covered by the `listmenu` command? So what does this command do?

<hr>

**Reported by:** @nianfei97
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#254]</sub>

**Comment by px1099** [comment]
Need justification of the existence of the `viewallmenu` command

**Comment by px1099** [comment]
Another way to phrase it:
Is the command `viewallmenu` even necessary?
