### ISSUE TITLE
Multiple names allowed

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-F09-2/main#157]
**Describe the bug**
The same person can be added to the member list when I type in the same person's name in a separate command but in different casing.

**To Reproduce**
1. Type: `addmember kang ting` and press "ENTER".
2. Type `addmember Kang Ting` and press "ENTER".
3. Type `listmembers` and press "ENTER".
![image](https://user-images.githubusercontent.com/35756209/47906257-d21e7300-dec3-11e8-99e3-c644fe1da098.png)

**Expected behavior**
Message should output "This member already exists in the address book", as it happens when I type the same person's name **in the same letter casing**. However, when I type the same person's name of different casing (see the steps above), the expected behavior does not show.

<hr>

**Reported by:** @jylee-git
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#284]</sub>

**Comment by kangmingtay** [comment]
I'll add another field called phone number so there's more differentiation between 2 members with the same name
