### ISSUE TITLE
User guide not updated for deletemenu

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-F09-2/main#158]
**Describe the bug**

**To Reproduce**
1. Enter "viewallmenu"
2. Press ENTER key
3. See error message: "Invalid command format."

**Expected behavior**
A list of all the menus should appear after keying in the "viewallmenu" command as specified first step of the deletemenu command in the user guide

**Screenshots**

![image](https://user-images.githubusercontent.com/35756915/47906726-d39c6b00-dec4-11e8-9287-f5b93bb7e0da.png)

<hr>

**Reported by:** @jeremyinelysium
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#309]</sub>

**Comment by px1099** [comment]
Closed. 
Reason: being the same problem as #156 & user misunderstood the command

**Comment by px1099** [comment]
Need to fix UG
