### ISSUE TITLE
Inconsistent terminology in UG

### ISSUE THREAD

**Issue by cs2113-bot-feedback** [CS2113-AY1819S1-F09-2/main#161]
**Describe the bug**
There appear to be two separate things in RMS, `customer`s, as described in section 3.4, and `member`s, as described in section 3.2. These two appear to be the same, since commands in 3.4 seem to work on `member`s.

<hr>

**Reported by:** @nianfei97
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#409]</sub>

**Comment by px1099** [comment]
Suggested improvement:
Add a terminology section to the user guide.
