### ISSUE TITLE
Commands from AB3 are still listed in the help window.

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-F09-2/main#166]
**Describe the bug**
Commands like `add`, `delete`, `clear`, etc. are still shown in the help window despite not having any relevance to the app anymore.

**To Reproduce**
1. Execute `help`.

**Screenshots**
![image](https://user-images.githubusercontent.com/35740636/47908087-7fdf5100-dec7-11e8-8a99-de275110a232.png)

<hr>

**Reported by:** @nianfei97
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#621]</sub>

**Comment by px1099** [comment]
Closed.
Reason: being the subproblem of #160
