### ISSUE TITLE
FORMAT and EXAMPLE of AddEmployee command is not consistent in UserGuide.adoc

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-F09-2/main#167]
**Describe the bug**
For the Add Employee command in UserGuide.adoc, the format and example given differs. With that, I am unable to add a new employee into the system if i were to follow the FORMAT strictly; and doing so will result in message "Invalid command format". See the extract of the UserGuide.adoc below: 
![image](https://user-images.githubusercontent.com/35756209/47907619-8e793880-dec6-11e8-9863-e4e4e9b96fa4.png)

i.e.: Do i need to use the `n/` prefix when specifying the name of the employee 
(`addemp n/Ah Tan p/9191....`) or not (`addemp Ah Tan p/9191...`)?

**To Reproduce**
1. Type the following command and press "ENTER":
![image](https://user-images.githubusercontent.com/35756209/47907515-625db780-dec6-11e8-8482-b8b217415213.png)

2. See error
![image](https://user-images.githubusercontent.com/35756209/47907484-51ad4180-dec6-11e8-998d-21bab99957b6.png)

**Expected behavior**
The employee "Ah Tan" should be added.

<hr>

**Reported by:** @jylee-git
**Severity:** `High`

<sub>[original: nusCS2113-AY1819S1/pe-1#676]</sub>

**Comment by px1099** [comment]
Closed.
Reason: being the same problem as #164
