### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-F09-2/main#169]
BUG: Employees can have the same and everyone can check in and out at the same time. 
Perhaps not really a bug, but not very logical for such a software.
1. Create 2 or more employees with the same name, e.g John Doe, randomly fill the other fields using the addemp command.
2. Ulse the clockIn command to 'clockIn John Doe'.
3. Use statsemp to list the employees currently on duty and clocked in, we realise there are 2 John Does clocked in.
4. Use clockOut, then use statsemp again to see the employees on duty. Both John Does have appeared to clockOut. 
Expected: Expect only 1 John Doe to clock in, logically, what if I really have employees with the same name, they can possibly come in and out at the same time.

<hr>

**Reported by:** @tztzt
**Severity:** `Low`

<sub>[original: nusCS2113-AY1819S1/pe-1#709]</sub>

**Comment by px1099** [comment]
Closed.
Reason: being the same problem as #159 & #162
