### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-F09-2/main#170]
Problem:
No notification to know I have entered an incorrect command, and its annoying to have to type everything in again.
Solution:
Create an error message to inform me when I entered an invalid command, then show the list of commands under it.
Save the commands I have entered and leave it in the box so i can fix the spelling error to key it in without the hassle.

Problem:
Employees have no enforced uniqueness. I can have 10 John Does and they can all clock in simultaneously and clock out simultaneously. I cannot control each person individually.
Solution:
Have a method to enforce unique employees, either by comparing name or the entire employee information, or clock in using another field rather than name.

Problem:

<hr>

**Reported by:** @tztzt
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#711]</sub>

**Comment by px1099** [comment]
Suggested improvement: Display the entered input
