### ISSUE TITLE
Implementation of code coverage

### ISSUE THREAD

**Issue by kangmingtay** [CS2113-AY1819S1-F09-2/main#45]
https://github.com/nusCS2113-AY1819S1/addressbook-level4/blob/master/docs/LearningOutcomes.adoc#use-code-coverage-code-lo-codecoverage-code

**Comment by kangmingtay** [comment]
Would be useful to know how many LOC is covered by our tests

**Comment by px1099** [comment]
Pull request #116 : setup coverage and coveralls
